<FirstScreen>:
    GridLayout:
        cols: 1
        spacing: 10
        Image:
            size_hint_y: 0.8
            id: img
        TextInput:
            size_hint_y: 0.05
            id: user_query
        Button:
            text: "Click here"
            size_hint_y: 0.15
            on_press: root.search_image()
<RootWidget>:
    FirstScreen:
        id: first_screen
        name: "first_screen"